<?php 	
		$this->load->view('complementos/sesion');
		$this->load->view('plantilla/head');
		$this->load->view('plantilla/header');
		$this->load->view('plantilla/nav/configuracion');
		$this->load->view('interfaz/configuracion/Monitoreo_Usuario_sa');
		//$this->load->view('interfaz/inicio/captura_de_datos_cfdi33');
		$this->load->view('plantilla/footer');
 ?>