<?php   
    $this->load->view('complementos/sesion');
    $this->load->view('plantilla/head');
    $this->load->view('plantilla/header');
    $this->load->view('plantilla/nav/configuracion');
    //$this->load->view('interfaz/configuracion/Privilegios_sa');
    //$this->load->view('interfaz/inicio/captura_de_datos_cfdi33');
    $this->load->view('interfaz/configuracion/Privilegios_sa_usuarios');
    //$this->load->view('complementos/formularios/configuraciones/ventanas_emergentes/Privilegios_sa_usuarios');
    $this->load->view('plantilla/footer');
 ?>